### ISSUE TITLE
'gossh vault encrypt' get plaintext that to be encrypted from prompt

### ISSUE THREAD

**Issue by nlcwyggyxdr** [windvalley/gossh#24]
Hi, thanks for your excellent work. Currently command `gossh vault encrypt` only obtains the plaintext to be encrypted from the argument. For security reasons, can you consider adding the feature of obtaining plaintext from promt?

For example:

```text
$ gossh vault encrypt -V ./vault-pass.txt
Plaintext:
Confirm plaintext:
```

**Comment by windvalley** [comment]
Thank you for your suggestion, it sounds like a good proposal. I will add this feature in the next minor version.

**Comment by nlcwyggyxdr** [comment]
@windvalley Awesome, thanks!
