### ISSUE TITLE
AIX make crashed  - undefined: fsnotify.Watcher

### ISSUE THREAD

**Issue by arozehnal** [windvalley/gossh#35]
AIX v.7.2
go env
GO111MODULE=""
GOARCH="ppc64"
GOBIN=""
GOCACHE=.
GOENV=
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="ppc64"
GOHOSTOS="aix"
GOINSECURE=""
GOMODCACHE="/home/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="aix"
GOPATH="/home/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/freeware/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/freeware/lib/golang/pkg/tool/aix_ppc64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOPPC64="power8"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/go/src/gossh/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -maix64 -pthread -mcmodel=large -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1254645141=/tmp/go-build -gno-record-gcc-switches"

==========> Building binary 'gossh' v1.15.1 for aix ppc64
 github.com/spf13/viper
../../pkg/mod/github.com/spf13/viper@v1.10.0/watch.go:8:25: undefined: fsnotify.Watcher
../../pkg/mod/github.com/spf13/viper@v1.10.0/watch.go:11:18: undefined: fsnotify.NewWatcher
make[1]: *** [scripts/makefiles/go.makefile:54: go.build.aix_ppc64.gossh] Error 1
make: *** [Makefile:43: build] Error 2

I found a similar case https://github.com/spf13/viper/issues/1416
Wouldn't it be possible to solve/bypass it in a similar way?

**Comment by windvalley** [comment]
@arozehnal I've fixed the issue. Try it again, and thanks for the feedback.

**Comment by arozehnal** [comment]
Thanks for the very quick fix.
gosh successfully created.
