### ISSUE TITLE
这个程序在openeuler操作系统上执行的时候，客户端和服务端握手过程中用于主机密钥验证的算法不匹配

### ISSUE THREAD

**Issue by sengluxia** [windvalley/gossh#38]
具体报错提示如下
199.1.1.60 | 2024-10-20 09:41:30.184446 | FAILED >>
ssh: handshake failed: ssh: no common algorithm for host key; client offered: [ssh-rsa-cert-v01@openssh.com ssh-dss-cert-v01@openssh.com ecdsa-sha2-nistp256-cert-v01@openssh.com ecdsa-sha2-nistp384-cert-v01@openssh.com ecdsa-sha2-nistp521-cert-v01@openssh.com ssh-ed25519-cert-v01@openssh.com ecdsa-sha2-nistp256 ecdsa-sha2-nistp384 ecdsa-sha2-nistp521 ssh-rsa ssh-dss ssh-ed25519], server offered: [rsa-sha2-512 rsa-sha2-256 sm2]

**Comment by windvalley** [comment]
客户端和服务端的openssh都是什么版本，是否版本差距较大，建议更新下openssh试试

**Comment by sengluxia** [comment]
> 客户端和服务端的openssh都是什么版本，是否版本差距较大，建议更新下openssh试试

 我们是国企单位，使用的是基于openeuler操作系统的凝思操作系统，更换openssh版本不太可能。
 openssh 的服务端和客户端版本都是 8.2

**Comment by windvalley** [comment]
这个问题和gossh工具本身没啥太大关系。我这没有你的问题环境，爱莫能助，建议你从网络上找下解决方案，应该是需要调整下ssh客户端或服务端的配置文件，以适配相关算法。

**Comment by sengluxia** [comment]
> 这个问题和gossh工具本身没啥太大关系。我这没有你的问题环境，爱莫能助，建议你从网络上找下解决方案，应该是需要调整下ssh客户端或服务端的配置文件，以适配相关算法。

好的，多谢
